### ISSUE TITLE
Add the jules-ign-reader to JCoRe

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-base#13]
Just convert it to the JCoRe conventions.

**Comment by AllesEins** [comment]
postponed to 2.3 update: "bioc" dependency wasn't working? Since I have no time to properly look into this issue and I want to roll out a 2.2 update (adding dh components & medical german models for sentence segmenters, tokenizers and pos taggers)

**Comment by fmatthies** [comment]
Is this task done?
The 2.3.0-SNAPSHOT branch contains the ign-reader and the test is  working.

**Comment by khituras** [comment]
Then it appears it’s done :-D I’m sorry, I apparently just forgot to close the issue.
