### ISSUE TITLE
de.julielab.jcore.types.AbstractPart in jcore-type-priorities.xml

### ISSUE THREAD

**Issue by pkluegl** [JULIELab/jcore-base#15]
I am looking for the type `de.julielab.jcore.types.AbstractPart` mentioned in `jcore-type-priorities.xml`, but I cannot find it in the type systems. Did I miss it?

**Comment by khituras** [comment]
That should actually be de.julielab.jcore.types.AbstractSection. This has been subject to more recent changes and obviously we missed the priorities file. The priorities are not complete and we don't use them internally. Do you require the priorities?

**Comment by pkluegl** [comment]
There is some exception when I try to run some AE with uimaFIT: Undefined type "de.julielab.jcore.types.AbstractPart" in type priority list.

**Comment by khituras** [comment]
If you don’t need the priorities, you could leave them out. We should better remove them altogether, really.

**Comment by khituras** [comment]
How are you running the AEs? I use them frequently with UIMA fit and never ran into this issue, which is why the bug is still there.

**Comment by pkluegl** [comment]
`SimplePipeline.runPipeline(collectionReaderDescription, analysisEngineDescriptionArray);`

btw, are there jcas cover classes for the types? I canot find them, and also no jcasgen-maven-plugin

**Comment by khituras** [comment]
jcore-types contains the cover classes. The jcasgen-maven-plugin should absolutely go there, too.

**Comment by pkluegl** [comment]
So the cover classes are manually created and not committed right now? I just trying to get the components up and running with a local workspace (I modified the type priorities).

**Comment by khituras** [comment]
Yes, currently we use JCasGen manually to build the cover classes and package them into a Maven artefact which is then deployed to Maven Central. The classes themselves are not committed to the source code repository.

**Comment by pkluegl** [comment]
I have some problems building jcore-types in order to use the adapted priorities. There seems to be some encoding problem in the description of the types:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project jcore-types: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - C:\Users\pkluegl\git\jcore-base\jcore-types\src\main\java\de\julielab\jcore\types\Acronym.java:12: error: unmappable character for encoding UTF-8
[ERROR] /** Abbreviation includes acronyms ???written as the initial letter or letters of words, and pronounced on the basis of this abbreviated written form.???
```

**Comment by pkluegl** [comment]
btw, thanks for all the support and help :-)

**Comment by khituras** [comment]
You're welcome :-) I'm sorry our tools give you so much trouble!
Regarding the encoding issue: You're right, there are a few weird codes in there. They are in the definition of the Acronym type which is located in the jcore-morpho-syntax-types.xml descriptor.
I committed a fixed version to branch 2.2. I hope that's everything from the coding side. I can't say because on my system, I don't get this error.

**Comment by AllesEins** [comment]
is this solved; we need to check?

**Comment by khituras** [comment]
I haven't seen this error in a while now. Closing for now.
