### ISSUE TITLE
mst-parser: not working in cpe

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#16]
... as the title says.
Either it has to do with some missing infos in the cpe itself, or with the unconventional way of handling shared resources.
Pipeline crashes, because it doesn't find the config file (that's only a deduction and nothing that is reported).

**Comment by AllesEins** [comment]
I think it's better to focus on an implementation of the MATE tools dependency parser:
* it performs better on GENIA than MST
* it would solve our trove issue

**Comment by khituras** [comment]
I think I fixed this a while ago. Reopen if there a more issues.
