### ISSUE TITLE
jsbd/jtbd: mallet

### ISSUE THREAD

**Issue by AllesEins** [JULIELab/jcore-base#21]
they both utilize now the "official mallet" artifact from Maven Central and not our "homebrewn" mallet version. The new performance for the FraMed corpus is documented. Need to check for e.g. Genia as well?!

**Comment by khituras** [comment]
But wouldn't that mean that newly trained models would have a lower performance?

Von meinem iPhone gesendet

**Comment by AllesEins** [comment]
They have... but just (negligibly?) smaller: see [1] for the reason

**FraMed**: 10-fold-crossvalidation

| *JSBD* | **F-Score** | **Accuracy** |
|--------|-------------|--------------|
| official Mallet | 0.993 | 0.985 |
| modified Mallet [1] | 0.994 | 0.987 |

| *JTBD* | **F-Score** | **Accuracy** |
|--------|-------------|--------------|
| official Mallet | 0.995 | 0.992 |
| modified Mallet [1] | 0.996 | 0.992 |

[1] these are the figures from the 2014 LREC paper; I haven't been able to reproduce them (and that was the reason why I tried the official Mallet artifact) because I couldn't train a model with at least one of JSBD & JTDB (can't recall which) but also couldn't do a crossvalidation with both.
Training was necessary as I wanted to provide FraMed models with the new JCoRe update.

**Comment by AllesEins** [comment]
**BioMed Corpus** (Genia, PennBio, Medline Abstracts): 10-fold-crossvalidation

| *JSBD* | **F-Score** | **Accuracy** |
|--------|-------------|--------------|
| official Mallet | 0.999 | 0.997 |
| modified Mallet [1] | ??? | 0.998 |

| *JTBD* | **F-Score** | **Accuracy** |
|--------|-------------|--------------|
| official Mallet |  |  |
| modified Mallet [1] |  |  |

[1] these are the figures that are reported in the documentations; F-Score is not reported, only Accuracy

**Comment by khituras** [comment]
Seems legit :-)

Von meinem iPhone gesendet
