### ISSUE TITLE
JCoRe File Reader: adding features

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#23]
- [x] the file reader could use a small feature that allows it to also browse through subdirs

**Comment by AllesEins** [comment]
- [ ] it would also be beneficial if one could say if the input files are already segmented in sentences 
- [ ] and tokens

**Comment by chlor** [comment]
Extension of the FileReader to go into sub directories; new boolean parameter 'ReadSubDirs'. If this parameter is true, all directories are will be read, if not or the parameter has not been set, the FileReader read only the data in the given directory.

**Comment by fmatthies** [comment]
@egrygorova can you give an estimate on how long it will take you to finish this task? Thanks!

**Comment by egrygorova** [comment]
I finished the task, there is just a problem with the pull request.

**Comment by fmatthies** [comment]
Done, thanks!
