### ISSUE TITLE
Redundant annotation type lemma?

### ISSUE THREAD

**Issue by buechel** [JULIELab/jcore-base#30]
In the type system (jcore-morpho-syntax-types.xml), "lemma" is a feature of the annotation type token. The value of the lemma feature has to be of type lemma which in turn has only one feature of type string.

Why not deleting this intermediate lemma type and set the lemma feature of the type token to be a string right away?

**Comment by khituras** [comment]
One reason could actually be that this way, the Lemmas can be add to CAS indexes and directly iterated upon instead of iterating over all tokens and retrieving their Lemma feature.
However, I don’t really know what the advantage of this should be.

**Comment by buechel** [comment]
On the other hand, the design as it is right now forces you to set begin and start indexes for lemma annotations although these are in fact identical to the corresponding token annotation (see https://github.com/JULIELab/jcore-base/blob/master/jcore-stanford-lemmatizer/src/main/java/de/julielab/jcore/ae/stanford/lemma/StanfordLemmatizer.java line 54 and following).
