### ISSUE TITLE
Gene Species Assigner: Syso to Log message

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-base#34]
The log message "No organisms" is actually quite helpful during development. However, it is currently just a system.out.println. Please make that a logging message.

**Comment by khituras** [comment]
It would also nice if the document ID would be logged. For further development

**Comment by pikatech** [comment]
Turned into a Logger.debug() call.

**Comment by pikatech** [comment]
Logging of document ID has been implemented.
