### ISSUE TITLE
jcore mantra xml types unclear

### ISSUE THREAD

**Issue by egrygorova** [JULIELab/jcore-base#42]
There is no information about it.
Please write the README for this type system.

**Comment by hellrich** [comment]
Most MANTRA types are specific for the IEXML format used internally and during the CLEF-ER workshop, see Dietrich Rebholz-Schuhmann et al.: Entity Recognition in Parallel Multilingual Biomedical Corpora: The CLEF-ER Laboratory Overview. In: CLEF 2013 - Information Access Evaluation. Multilinguality, Multimodality, and Visualization. Valencia, Spain, September 23-26, 2013, pp. 353-367

**Comment by hellrich** [comment]
de.julielab.jcore.types.mantra.NER could be of general interest, it extends our "Annotations" type with  certainty (of a classifier judgment, not to be confused with Christine Engelmann's work) and UMLS semantic groups.

**Comment by hellrich** [comment]
Ok, I was confused myself, my comments are in regard to the MANTRA extension of our UIMA type system. The jcore-mantra-xml-types are only used for (de)serializing the IEXML format in our reader/consumer.
