### ISSUE TITLE
JEmAS too little information

### ISSUE THREAD

**Issue by egrygorova** [JULIELab/jcore-base#44]
Please write the README for JEmAS.

**Comment by fmatthies** [comment]
Please provide some infos for JEmAS! (see the README in the JCoRe Skeleton: https://github.com/JULIELab/jcore-misc/tree/master/jcore-component-skeleton)

**Comment by egrygorova** [comment]
Hallo Franz,

ich wollte mit dir einen Termin ausmachen, um meine neuen Aufgaben zu  
besprechen, mir ist da nämlich einiges unklar.
Wann hast du diese Woche Zeit?

Gruß,
Elena
Quoting Franz Matthies <notifications@github.com>:

**Comment by egrygorova** [comment]
https://github.com/JULIELab/jcore-base/tree/2.3.0-SNAPSHOT/jcore-jemas-ae

I provided a basic README in the 2.3.0-SNAPSHOT, 
@buechel please complete it
