### ISSUE TITLE
jcore-txt-consumer: add pos feature & README

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#46]
right now the recently added consumer just outputs sentences (one per line) and tokens (whitespace separated).
it also needs a feature to add POS information to each token if available (& desired) so that the POS tag is appended to each token with a designated delimiter (e.g. `_` or `|`).
Furthermore README :)
@egrygorova: Please contact me when you're done with your former task so we can tackle this one.

**Comment by egrygorova** [comment]
ok, i will contact you soon, no later than friday.

**Comment by fmatthies** [comment]
Done & Thanks!
