### ISSUE TITLE
PMC Reader no information

### ISSUE THREAD

**Issue by egrygorova** [JULIELab/jcore-base#50]
please provide some information about that component, hence I can make a README for it

**Comment by fmatthies** [comment]
@egrygorova, please provide a basic README with `capabilities` etc. as you did for the other components. @khituras or me can then fill out the missing parts

**Comment by egrygorova** [comment]
done, please fill out the missing parts
i made a new branch for this issue:  issue50-pmcReaderREADME

**Comment by khituras** [comment]
I did add the capabilities to the descriptor. Please be so kind to migrate these information into the README :-)

I also wrote actual documentation into the README as well as into the most important classes as JavaDoc. I hope the component counts as “documented” now :-D

**Comment by egrygorova** [comment]
okay, I completed the part with the capabilities :)

**Comment by egrygorova** [comment]
@fmatthies can we close this issue now? :-)

**Comment by fmatthies** [comment]
If there is a pull request and it's accepted, we can close it ;)
