### ISSUE TITLE
jcore-xmi-writer: SAXParseException

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#63]
the writer fails when encountering "bad" characters

> Caused by: org.xml.sax.SAXParseException; Trying to serialize non-XML 1.0 character: 

Maybe we could catch this error and skip the character when writing out (or add a parameter to the writer descriptor that makes it possible to choose what behavior is preferable).

**Comment by khituras** [comment]
Is there an example XML for a test? I had issues like this in the past and could solve it by using a specific XML parsing library. I would check on it if there is a test I could work with.

**Comment by fmatthies** [comment]
Thanks! Unfortunately it's a clinical document... and the error is thrown when creatig UIMA xmi's from a CAS.

**Comment by khituras** [comment]
Hm, but perhaps you could identify the character?
I had this error before. Actually, the CAS deserialisation wasn’t the problem: the deserialisation was. It handled characters beyond the Unicode BMP plain incorrectly. If you created the XMI in question yourself, you could check out the JCoReTools#deserializeXmi() method in jcore-utilities. It did fix my issue.

On another note, when using StAX, it might be necessary to employ the woodstox parser to fix such errors. But here we have SAX case, if I remember correctly.

**Comment by khituras** [comment]
Not handled due to a missing reproduction example.
