### ISSUE TITLE
List of components and projects

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#66]
Please provide a list with all components that are in `jcore-base 2.3.0-SNAPSHOT` as well as `jcore-projects 2.3.0-SNAPSHOT`

**Comment by egrygorova** [comment]
Components for jcore-base (2.3.0-SNAPSHOT):

1) JCoRe ACE Collection Reader
2) JCoRe Acronym Analysis Engine
3) JCoRe BioNLP Format Event Consumer
4) JCoRe BioNLP Format Reader
5) JCoRe BioSEM Analysis Engine
6) JCoRe CAS2Conll Consumer
7) JCoRe CAS2IOB Consumer
8) JCoRe Coordination Baseline Analysis Engine
9) JCoRe DTA Collection Reader
10) JCoRe ECN AE
11) JCoRe File Collection Reader
12) JCore Gene Species Assigner
13) JCoRe IEXML Consumer
14) JCoRe IEXML Collection Reader
15) JCore IGN Reader
16) JCoRe Named Entity Tagger Analysis Engine
17) JCoRe Part-of-Speech Tagging Analysis Engine
18) JCoRe Sentence Boundary Detection Analysis Engine
19) JCoRe Token Boundary Detection Analysis Engine
20) JCoRe Lingpipe Porterstemmer
21) JCoRe Lingpipe Gazetteer Analysis Engine
22) JCoRe Mantra XML Types
23) JCoRe Medxn Analysis Engine (looks incomplete)
24) JCore MScod2txt Reader
25) JCoRe MST Parser Analysis Engine
26) JCoRe MUC7 Collection Reader
27) JCoRe OpenNLP Chunker Wrapper
28) JCoRe OpenNLP Parser Wrapper
29) JCoRe OpenNLP POS Tagger Wrapper
30) JCoRe OpenNLP Sentence Segmenter Wrapper
31) JCoRe OpenNLP Tokenizer Wrapper
32) JCoRe PMC Collection Reader
33) JCoRe Stanford Lemmatizer
34) JCore Text Consumer
35) JCoRe Types
36) JCoRe Utilities
37) JCoRe XMI Collection Reader
38) JCoRe XMI Writer
39) JCoRe XML Mapper
40) JCoRe XML Collection Reader

**Comment by egrygorova** [comment]
Components for jcore-projects (2.3.0-SNAPSHOT)

1) BioNLP Shared Task 11 Model
2) JCoRe JNET BioMedical English Analysis Engine
3) JCoRe JPOS Medical German (FRAMED)
4) JCoRE JSBD BioMedical English Analysis Engine
5) JCoRe JSBD Medical German (FRAMED)
6) JCoRe JTBD BioMedical English Analysis Engine
7) JCoRe JTBD Medical German (FRAMED)
8) JCoRe LingPipe Gazetteer Dummy Implementation
9) JCoRe MEDLINE Reader
10) JCoRe MST Parser Genia 2008
11) JCoRe JCoRe OpenNLP Chunker Wrapper, Biomedical English
12) JCoRe OpenNLP Parser Wrapper, Biomedical English
13) JCoRe OpenNLP POS Tagger Wrapper, Biomedical English
14) JCoRe OpenNLP POS Tagger Wrapper, Medical German (FraMed)
15) JCoRe OpenNLP Sentence Segmenter Wrapper, Biomedical English
16) JCoRe OpenNLP Sentence Segmenter Wrapper, Medical German (FraMed)
17) JCoRe OpenNLP Tokenizer Wrapper, Biomedical English
18) JCoRe OpenNLP Tokenizer Wrapper, Medical German (FraMed)
19) JCoRe PubMed Reader

**Comment by khituras** [comment]
This issue is stale and will probably not persued any more. Closing.
