### ISSUE TITLE
Create Parameters docs for jcore-julielab-entity-evaluator-consumer

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-base#72]
Elena, would you be so kind to add the Parameters documentation to the README.md file in the mentioned component? All parameters are described in the descriptor, I think that should suffice. You would really help me.

**Comment by khituras** [comment]
Oh, I added a "TODO" as a marker to the appropriate position. This should  be removed when everything is done, of course.

**Comment by egrygorova** [comment]
ok, I think it's done :-)

**Comment by khituras** [comment]
Thank you so much :-)
