### ISSUE TITLE
Git merge artifacts in type priorities

### ISSUE THREAD

**Issue by bnczk** [JULIELab/jcore-base#91]
The [jcore-types type priority file](https://github.com/JULIELab/jcore-base/blob/master/jcore-types/src/main/resources/de/julielab/jcore/types/priorities/jcore-type-priorities.xml) still contains conflict markers. They are also present in the maven artifact of version 2.2.0.

**Comment by khituras** [comment]
Fixed in the new 2.3.0 release.  Thanks for reporting!
